### ISSUE TITLE
can not intall in laravel 5.5.35

### ISSUE THREAD

**Issue by askme-gpt** [johannesschobel/laravel-userhistory#1]
I require this package use dev version as follow ,but it seems that only support laravel 5.1.*

![image](https://user-images.githubusercontent.com/22534808/45140803-90848b00-b1e6-11e8-8529-7534882fc5ca.png)

**Comment by johannesschobel** [comment]
Yeah, that is because I initially developed the package for Laravel 5.1 .. this version is locked in the composer.json file..

Not sure, though, if it works on 5.1+ versions, as I have not tested it, but I guess it would.. you can provide a PR to migrate to the latest Laravel 5.7 version.. 

All the best
